# Generated by Django 4.2 on 2023-04-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_number", models.CharField(max_length=20, unique=True)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("2W", "Two Wheeler"),
                            ("3W", "Three Wheeler"),
                            ("4W", "Four Wheeler"),
                        ],
                        max_length=2,
                    ),
                ),
                ("vehicle_model", models.CharField(max_length=100)),
                ("vehicle_description", models.TextField()),
            ],
        ),
    ]
